### ISSUE TITLE
AttributeError: module 'stimela' has no attribute 'is_logger_initialized'

### ISSUE THREAD

**Issue by Kincaidr** [caracal-pipeline/stimela2#139]
Hi,

Starting up caracal gives me this error:

```
(caracal-venv) kincaid@ike:/vault-ike/kincaid/Software/caracal$ caracal
Traceback (most recent call last):
  File "/home/kincaid/venv/caracal-venv/bin/caracal", line 7, in <module>
    exec(compile(f.read(), __file__, 'exec'))
  File "/net/sinatra/vault-ike/kincaid/Software/caracal/bin/caracal", line 4, in <module>
    import caracal.main as main
  File "/net/sinatra/vault-ike/kincaid/Software/caracal/caracal/__init__.py", line 177, in <module>
    create_logger()
  File "/net/sinatra/vault-ike/kincaid/Software/caracal/caracal/__init__.py", line 125, in create_logger
    if stimela.is_logger_initialized():
AttributeError: module 'stimela' has no attribute 'is_logger_initialized
```

This is my first time using caracal with stimela2. It worked before using the older stimela versions.

**Comment by o-smirnov** [comment]
It's not compatible with stimela2 though...

Cheers,
Oleg

--

**Comment by Kincaidr** [comment]
Apologies got confused with `caracal-pipeline/stimela` repository
