### ISSUE TITLE
Formulas don't seem to work in List[str]

### ISSUE THREAD

**Issue by senkhxsi** [caracal-pipeline/stimela2#153]
I'm trying to take a parameter from a previous step and provide it as a formula in a List[str] and it's not being interpreted correctly ("steps.prc_phase_delay_selfcal.caltable" is the parameter in question):

```bash
──────────────────────────────────────────────────────────────────────────── vlba_phase_referencing_tutorial_recipe.prc_phase_selfcal ─────────────────────────────────────────────────────────────────────────────
2023-04-04 18:31:56 STIMELA.vlba_phase_referencing_tutorial_recipe.prc_phase_selfcal INFO: ### validated inputs                                                                                                    
2023-04-04 18:31:56 STIMELA.vlba_phase_referencing_tutorial_recipe.prc_phase_selfcal INFO: cab casatasks.gaincal:                                                                                                  
2023-04-04 18:31:56 STIMELA.vlba_phase_referencing_tutorial_recipe.prc_phase_selfcal INFO:   vis = tl016b_cal1.ms                                                                                                  
2023-04-04 18:31:56 STIMELA.vlba_phase_referencing_tutorial_recipe.prc_phase_selfcal INFO:   field = J1154+6022                                                                                                    
2023-04-04 18:31:56 STIMELA.vlba_phase_referencing_tutorial_recipe.prc_phase_selfcal INFO:   solint = 20s                                                                                                          
2023-04-04 18:31:56 STIMELA.vlba_phase_referencing_tutorial_recipe.prc_phase_selfcal INFO:   refant = FD                                                                                                           
2023-04-04 18:31:56 STIMELA.vlba_phase_referencing_tutorial_recipe.prc_phase_selfcal INFO:   minblperant = 3                                                                                                       
2023-04-04 18:31:56 STIMELA.vlba_phase_referencing_tutorial_recipe.prc_phase_selfcal INFO:   gaintype = G                                                                                                          
2023-04-04 18:31:56 STIMELA.vlba_phase_referencing_tutorial_recipe.prc_phase_selfcal INFO:   calmode = p                                                                                                           
2023-04-04 18:31:56 STIMELA.vlba_phase_referencing_tutorial_recipe.prc_phase_selfcal INFO:   parang = False                                                                                                        
2023-04-04 18:31:56 STIMELA.vlba_phase_referencing_tutorial_recipe.prc_phase_selfcal INFO:   gaintable = ['=steps.prc_phase_delay_selfcal.caltable']                                                               
2023-04-04 18:31:56 STIMELA.vlba_phase_referencing_tutorial_recipe.prc_phase_selfcal INFO:   interp = ['linear']                                                                                                   
2023-04-04 18:31:56 STIMELA.vlba_phase_referencing_tutorial_recipe.prc_phase_selfcal INFO:   caltable = tl016b_cal1.pcal                                                                                           
### running gaincal                                                                                                                                                                                                
# invoking callable casatasks.gaincal() using external interpreter                                                                                                                                                 
# 2023-04-04 18:31:57   SEVERE          Exception Reported: Table =steps.prc_phase_delay_selfcal.caltable does not exist.                                                                                          
# 2023-04-04 18:31:57   SEVERE  gaincal::::casa Task gaincal raised an exception of class RuntimeError with the following message: Table =steps.prc_phase_delay_selfcal.caltable does not exist.                   
# Traceback (most recent call last):                                                                                                                                                                               
#   File "<string>", line 17, in <module>                                                                                                                                                                          
#   File "/home/senkhxsi/venvs/stimela2_env/lib/python3.8/site-packages/casatasks/gaincal.py", line 391, in __call__                                                                                               
#     task_result = _gaincal_t( _pc.document['vis'], _pc.document['caltable'], _pc.document['field'], _pc.document['spw'], _pc.document['intent'], _pc.document['selectdata'], _pc.document['timerange'],          
_pc.document['uvrange'], _pc.document['antenna'], _pc.document['scan'], _pc.document['observation'], _pc.document['msselect'], _pc.document['solint'], _pc.document['combine'], _pc.document['preavg'],            
_pc.document['refant'], _pc.document['refantmode'], _pc.document['minblperant'], _pc.document['minsnr'], _pc.document['solnorm'], _pc.document['normtype'], _pc.document['gaintype'], _pc.document['smodel'],      
_pc.document['calmode'], _pc.document['solmode'], _pc.document['rmsthresh'], _pc.document['corrdepflags'], _pc.document['append'], _pc.document['splinetime'], _pc.document['npointaver'],                         
_pc.document['phasewrap'], _pc.document['docallib'], _pc.document['callib'], _pc.document['gaintable'], _pc.document['gainfield'], _pc.document['interp'], _pc.document['spwmap'], _pc.document['parang'] )        
#   File "/home/senkhxsi/venvs/stimela2_env/lib/python3.8/site-packages/casatasks/private/task_gaincal.py", line 125, in gaincal                                                                                   
#     mycb.setapply(t=0.0,table=gaintable\[igt],field=thisgainfield,                                                                                                                                               
#   File "/home/senkhxsi/venvs/stimela2_env/lib/python3.8/site-packages/casatools/calibrater.py", line 212, in setapply                                                                                            
#     return self._swigobj.setapply(type, t, table, field, interp, select, calwt, spwmap, opacity)                                                                                                                 
#   File "/home/senkhxsi/venvs/stimela2_env/lib/python3.8/site-packages/casatools/__casac__/calibrater.py", line 479, in setapply                                                                                  
#     return _calibrater.calibrater_setapply(self, *args, **kwargs)                                                                                                                                                
# RuntimeError: Table =steps.prc_phase_delay_selfcal.caltable does not exist.                                                                                                                                      
2023-04-04 18:31:57 STIMELA.vlba_phase_referencing_tutorial_recipe.prc_phase_selfcal ERROR: step 'vlba_phase_referencing_tutorial_recipe.prc_phase_selfcal' has failed, aborting the recipe                        
────────────────────────────────────────────────────────────────────────────────────────── detailed error report follows ──────────────────────────────────────────────────────────────────────────────────────────
        ⚠ step 'vlba_phase_referencing_tutorial_recipe.prc_phase_selfcal' has failed, aborting the recipe                                                                                                          
        └── error running cab 'casatasks.gaincal'                                                                                                                                                                  
            └── gaincal returns error code 1 after 0:00:01    
```

**Comment by o-smirnov** [comment]
OK, I see the problem, ``['=steps.prc_phase_delay_selfcal.caltable']`` is not treated as a legit formula, since it doesn't start with "=".

In fact the formula syntax doesn't currently recognize square brackets at all. https://github.com/caracal-pipeline/stimela/issues/152 also relates to this. I might get it working in the future once I improve my parser-fu sufficiently.

There is a workaround for your case in the meantime -- try ``=LIST(steps.prc_phase_delay_selfcal.caltable)``.

**Comment by o-smirnov** [comment]
Thanks to @JSKenyon this is now fixed  and available in R2.0.
