### ISSUE TITLE
Crash due to `List` parameters without a default

### ISSUE THREAD

**Issue by SpheMakh** [caracal-pipeline/stimela2#220]
This definition cannot be loaded using `configurat.load` 
```yaml
inputs:
  foo:
    dtype: List[File]
  bar:
   dtype: str
```
It gives the error below

```bash
Traceback (most recent call last):
  File "/home/sphemakh/work/softdev/simms/simms/parser_config/observe.py", line 9, in <module>
    config = load(command, use_sources=sources)
  File "/home/sphemakh/work/softdev/simms/simms/parser_config/utils.py", line 31, in load
    struct_args, _ = configuratt.load_nested([parser], structured=args_defn,
  File "/home/sphemakh/.cache/pypoetry/virtualenvs/simms-sTfgD1wW-py3.10/lib/python3.10/site-packages/scabha/configuratt/__init__.py", line 118, in load_nested
    subconf, deps = load(path, location=location, use_sources=use_sources, include_path=include_path)
  File "/home/sphemakh/.cache/pypoetry/virtualenvs/simms-sTfgD1wW-py3.10/lib/python3.10/site-packages/scabha/configuratt/__init__.py", line 52, in load
    conf, deps = resolve_config_refs(subconf, pathname=path, location=location, name=name, 
  File "/home/sphemakh/.cache/pypoetry/virtualenvs/simms-sTfgD1wW-py3.10/lib/python3.10/site-packages/scabha/configuratt/resolvers.py", line 351, in resolve_config_refs
    value1, deps = resolve_config_refs(value, pathname=pathname, name=name, 
  File "/home/sphemakh/.cache/pypoetry/virtualenvs/simms-sTfgD1wW-py3.10/lib/python3.10/site-packages/scabha/configuratt/resolvers.py", line 351, in resolve_config_refs
    value1, deps = resolve_config_refs(value, pathname=pathname, name=name, 
  File "/home/sphemakh/.cache/pypoetry/virtualenvs/simms-sTfgD1wW-py3.10/lib/python3.10/site-packages/scabha/configuratt/resolvers.py", line 351, in resolve_config_refs
    value1, deps = resolve_config_refs(value, pathname=pathname, name=name, 
  [Previous line repeated 3 more times]
  File "/home/sphemakh/.cache/pypoetry/virtualenvs/simms-sTfgD1wW-py3.10/lib/python3.10/site-packages/scabha/configuratt/resolvers.py", line 364, in resolve_config_refs
    for i, value in enumerate(conf._iter_ex(resolve=False)):
  File "/home/sphemakh/.cache/pypoetry/virtualenvs/simms-sTfgD1wW-py3.10/lib/python3.10/site-packages/omegaconf/listconfig.py", line 572, in _iter_ex
    self._format_and_raise(key=None, value=None, cause=e)
  File "/home/sphemakh/.cache/pypoetry/virtualenvs/simms-sTfgD1wW-py3.10/lib/python3.10/site-packages/omegaconf/base.py", line 231, in _format_and_raise
    format_and_raise(
  File "/home/sphemakh/.cache/pypoetry/virtualenvs/simms-sTfgD1wW-py3.10/lib/python3.10/site-packages/omegaconf/_utils.py", line 899, in format_and_raise
    _raise(ex, cause)
  File "/home/sphemakh/.cache/pypoetry/virtualenvs/simms-sTfgD1wW-py3.10/lib/python3.10/site-packages/omegaconf/_utils.py", line 797, in _raise
    raise ex.with_traceback(sys.exc_info()[2])  # set env var OC_CAUSE=1 for full trace
  File "/home/sphemakh/.cache/pypoetry/virtualenvs/simms-sTfgD1wW-py3.10/lib/python3.10/site-packages/omegaconf/listconfig.py", line 566, in _iter_ex
    raise TypeError("Cannot iterate a ListConfig object representing None")
omegaconf.errors.ConfigTypeError: Cannot iterate a ListConfig object representing None
    full_key: element_choices
    reference_type=Optional[List[Any]]
    object_type=list
(simms-sTfgD1wW-py3.10) sphemakh@sibongile:~/work/softdev/simms$ poetry run python simms/parser_config/observe.py --help
Traceback (most recent call last):
  File "/home/sphemakh/work/softdev/simms/simms/parser_config/observe.py", line 9, in <module>
    config = load(command, use_sources=sources)
  File "/home/sphemakh/work/softdev/simms/simms/parser_config/utils.py", line 31, in load
    struct_args, _ = configuratt.load_nested([parser], structured=args_defn,
  File "/home/sphemakh/.cache/pypoetry/virtualenvs/simms-sTfgD1wW-py3.10/lib/python3.10/site-packages/scabha/configuratt/__init__.py", line 118, in load_nested
    subconf, deps = load(path, location=location, use_sources=use_sources, include_path=include_path)
  File "/home/sphemakh/.cache/pypoetry/virtualenvs/simms-sTfgD1wW-py3.10/lib/python3.10/site-packages/scabha/configuratt/__init__.py", line 52, in load
    conf, deps = resolve_config_refs(subconf, pathname=path, location=location, name=name, 
  File "/home/sphemakh/.cache/pypoetry/virtualenvs/simms-sTfgD1wW-py3.10/lib/python3.10/site-packages/scabha/configuratt/resolvers.py", line 351, in resolve_config_refs
    value1, deps = resolve_config_refs(value, pathname=pathname, name=name, 
  File "/home/sphemakh/.cache/pypoetry/virtualenvs/simms-sTfgD1wW-py3.10/lib/python3.10/site-packages/scabha/configuratt/resolvers.py", line 351, in resolve_config_refs
    value1, deps = resolve_config_refs(value, pathname=pathname, name=name, 
  File "/home/sphemakh/.cache/pypoetry/virtualenvs/simms-sTfgD1wW-py3.10/lib/python3.10/site-packages/scabha/configuratt/resolvers.py", line 351, in resolve_config_refs
    value1, deps = resolve_config_refs(value, pathname=pathname, name=name, 
  [Previous line repeated 3 more times]
  File "/home/sphemakh/.cache/pypoetry/virtualenvs/simms-sTfgD1wW-py3.10/lib/python3.10/site-packages/scabha/configuratt/resolvers.py", line 364, in resolve_config_refs
    for i, value in enumerate(conf._iter_ex(resolve=False)):
  File "/home/sphemakh/.cache/pypoetry/virtualenvs/simms-sTfgD1wW-py3.10/lib/python3.10/site-packages/omegaconf/listconfig.py", line 572, in _iter_ex
    self._format_and_raise(key=None, value=None, cause=e)
  File "/home/sphemakh/.cache/pypoetry/virtualenvs/simms-sTfgD1wW-py3.10/lib/python3.10/site-packages/omegaconf/base.py", line 231, in _format_and_raise
    format_and_raise(
  File "/home/sphemakh/.cache/pypoetry/virtualenvs/simms-sTfgD1wW-py3.10/lib/python3.10/site-packages/omegaconf/_utils.py", line 899, in format_and_raise
    _raise(ex, cause)
  File "/home/sphemakh/.cache/pypoetry/virtualenvs/simms-sTfgD1wW-py3.10/lib/python3.10/site-packages/omegaconf/_utils.py", line 797, in _raise
    raise ex.with_traceback(sys.exc_info()[2])  # set env var OC_CAUSE=1 for full trace
  File "/home/sphemakh/.cache/pypoetry/virtualenvs/simms-sTfgD1wW-py3.10/lib/python3.10/site-packages/omegaconf/listconfig.py", line 566, in _iter_ex
    raise TypeError("Cannot iterate a ListConfig object representing None")
omegaconf.errors.ConfigTypeError: Cannot iterate a ListConfig object representing None
    full_key: element_choices
    reference_type=Optional[List[Any]]
    object_type=list
```

The error goes away after I change `inputs.foo.dtype` to `File`

**Comment by sphemakh** [comment]
The error doesn't show up if `inputs.foo` has a default value.

**Comment by o-smirnov** [comment]
Interesting.... and if you set ``dtype: List[File]`` and ``default: []``, does it go away?

**Comment by sphemakh** [comment]
Oops! The error went away when I ran the script on a different machine. It also went away after I set `use_cache=False`, so it seems my run at the office had cached something funky. 

![](https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExZG4waHlpMTBlaGtvaG43aGk3c2s4ZzdrdmhrdmMyNmg2aDNoc3IxMCZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/Q8OIR3s0hT5p6/giphy.gif)
