### ISSUE TITLE
stimela 2.0.0rc9 fails with exception if git is not installed

### ISSUE THREAD

**Issue by tmolteno** [caracal-pipeline/stimela2#223]
Stimela 2.0.0rc9 fails if git is not installed. The error is as follows:

```
root@2df4f513fd13:/sim_data# stimela -v run basics.yml 
2024-02-08 00:53:14 STIMELA INFO: starting                                                                                                                                                 
2024-02-08 00:53:14 STIMELA DEBUG: verbose output enabled                                                                                                                                  
2024-02-08 00:53:14 STIMELA INFO: include paths are /root/.stimela:/root/lib/stimela:/usr/lib/stimela:/usr/local/lib/stimela:.                                                             
/root/.cache/stimela-configs does not exist
2024-02-08 00:53:14 STIMELA INFO: loading configuration                                                                                                                                    
Traceback (most recent call last):
  File "/usr/local/bin/stimela", line 8, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1685, in invoke
    super().invoke(ctx)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/stimela/main.py", line 83, in cli
    stimela.CONFIG = config.load_config(extra_configs=config_files, extra_dotlist=config_dotlist, include_paths=include,
  File "/usr/local/lib/python3.8/dist-packages/stimela/config.py", line 184, in load_config
    dependencies = get_initial_deps()
  File "/usr/local/lib/python3.8/dist-packages/stimela/config.py", line 104, in get_initial_deps
    dependencies.add(STIMELA_DIR, version=stimela.__version__)              
  File "/usr/local/lib/python3.8/dist-packages/scabha/configuratt/deps.py", line 68, in add
    gitinfo = self._get_git_info(dirname)
  File "/usr/local/lib/python3.8/dist-packages/scabha/configuratt/deps.py", line 111, in _get_git_info
    branches = subprocess.check_output("git -c color.ui=never branch -a -v -v".split(), 
  File "/usr/lib/python3.8/subprocess.py", line 415, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.8/subprocess.py", line 493, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib/python3.8/subprocess.py", line 858, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.8/subprocess.py", line 1704, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'git'
```

Catching FNF exception around line 111 of /scabha/configuratt/deps.py might be helpful here.  Installing git fixes the problem.

**Comment by o-smirnov** [comment]
Ooops! Try the ``issue-223`` branch please.
