### ISSUE TITLE
ImportError: cannot import name 'task_stats' from partially initialized module 'stimela' 

### ISSUE THREAD

**Issue by Kincaidr** [caracal-pipeline/stimela2#68]
Hi,

Ill be posting `kube` related errors here. The first one I get is:

```
(stimela_venv) kincaid@ike:/vault-ike/kincaid/xova_analysis_new_bda/xova_bda$ stimela exec selfcal-boom-new.yml boom obs=L1 -s image-4:image-4
Traceback (most recent call last):
  File "/home/kincaid/stimela_venv/bin/stimela", line 11, in <module>
    load_entry_point('stimela', 'console_scripts', 'stimela')()
  File "/home/kincaid/stimela_venv/lib/python3.8/site-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/home/kincaid/stimela_venv/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2852, in load_entry_point
    return ep.load()
  File "/home/kincaid/stimela_venv/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2443, in load
    return self.resolve()
  File "/home/kincaid/stimela_venv/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2449, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/vault-ike/kincaid/Software/stimela2/stimela/__init__.py", line 61, in <module>
    from .stimelogging import logger, log_exception
  File "/vault-ike/kincaid/Software/stimela2/stimela/stimelogging.py", line 15, in <module>
    from . import task_stats
ImportError: cannot import name 'task_stats' from partially initialized module 'stimela' (most likely due to a circular import) (/vault-ike/kincaid/Software/stimela2/stimela/__init__.py)
```

**Comment by o-smirnov** [comment]
Ah, that's me forgetting to git add a new file. Please git pull and try again.

**Comment by Kincaidr** [comment]
Works now. However, sticking to `kube` branch-related errors. I am still getting the `'SubstitutionErrorList' object has no attribute 'errors'` error I mentioned at the end of issue #65. I will open a separate issue for this shortly.
