### ISSUE TITLE
`skip` not working as expected

### ISSUE THREAD

**Issue by Athanaseus** [caracal-pipeline/stimela2#73]
I have `skip` in one of my steps, but no skip parameter is defined in my recipe.
Steps are skipped regardless of what is set to `skip`.

```     
   calibrate-0: 
      info: invokes cubical to correct for parallactic angle
      _use: lib.steps.cubical.base
      params:
        data.ms: =recipe.ms
        ...
        k.save-to: "{current.out.dir}/Ksol-{recipe.label}"
        skip: =recipe.blah
```
NB: No variable blah in the recipe

But if nothing is set to skip the step, everything runs fine.
```     
   calibrate-0: 
      info: invokes cubical to correct for parallactic angle
      _use: lib.steps.cubical.base
      params:
        data.ms: =recipe.ms
        ...
        k.save-to: "{current.out.dir}/Ksol-{recipe.label}"
        skip:
```

command: `stimela -C run -s calibrate-0:image_pol-0 pica-time.yml pictor`

**Comment by o-smirnov** [comment]
Could you please run with ``stimela -v``. This will produce a slew of debug output -- I'm interested in the line that says "dynamic skip attribute evaluation returns ..." when the offending step is invoked.

**Comment by Athanaseus** [comment]
command: `stimela -v -C run -s calibrate-0:image_pol-0 pica-time.yml pictor`

```
2022-10-25 15:03:22 STIMELA.pictor INFO: processing step 'calibrate-0'
2022-10-25 15:03:22 STIMELA.pictor ^[[1m^[[92mINFO:   (invokes cubical to correct for parallactic angle)^[[0m                                                                                  
2022-10-25 15:03:22 STIMELA.pictor.calibrate-0 DEBUG: dynamic skip attribute evaluation returns {'skip': 'recipe.blah'}
2022-10-25 15:03:22 STIMELA.pictor.calibrate-0 DEBUG: validating inputs ['info', 'config', 'steps', 'previous', 'recipe', 'root', 'current']
2022-10-25 15:03:22 STIMELA.pictor INFO: skipping step based on setting of 'recipe.blah'
2022-10-25 15:03:22 STIMELA.pictor.calibrate-0 DEBUG: validating outputs
2022-10-25 15:03:22 STIMELA.pictor.calibrate-0 DEBUG: ### validated outputs
2022-10-25 15:03:22 STIMELA.pictor.calibrate-0 DEBUG: cab calibrate-0:
```

**Comment by o-smirnov** [comment]
OK please pull the branch and try again.

**Comment by Athanaseus** [comment]
same command: `stimela -v -C run -s calibrate-0:image_pol-0 pica-time.yml pictor`

```
2022-10-25 16:46:09 STIMELA DEBUG: config dependency /home/ramaila/software/stimela2/scabha/configuratt/cache.py, version: None, mtime: Sat Oct 22 10:28:02 2022, mtime_str: Sat Oct 22       
10:28:02 2022, md5hash: 28cbc2986c8abcb18336161b1a8f80c8, git: {'branch': 'kube                          7f15327 [origin/kube] fixes #73. Cleanups to UNSET treatment, particularly for       
for-loop iterants', 'describe': 'heads/kube-0-g7f153276525f4256', 'remotes': ['origin\thttps://github.com/caracal-pipeline/stimela2.git (fetch)',                                             
'origin\thttps://github.com/caracal-pipeline/stimela2.git (push)']}                                                                                                                           
2022-10-25 16:46:09 STIMELA DEBUG: config dependency /home/ramaila/software/stimela2/stimela/cargo/base/casa/casa.yaml, origin: /home/ramaila/software/stimela2/stimela                       
2022-10-25 16:46:09 STIMELA DEBUG: config dependency /home/ramaila/software/stimela2/stimela/cargo/lib/params/wsclean.yaml, origin: /home/ramaila/software/stimela2/stimela                   
2022-10-25 16:46:09 STIMELA DEBUG: config dependency /home/ramaila/software/stimela2/stimela/cargo/lib/params/casa.yaml, origin: /home/ramaila/software/stimela2/stimela                      
2022-10-25 16:46:09 STIMELA DEBUG: config dependency /home/ramaila/software/stimela2/stimela/cargo/cab/fitstool_stack.yaml, origin: /home/ramaila/software/stimela2/stimela                   
2022-10-25 16:46:09 STIMELA DEBUG: config dependency /home/ramaila/software/stimela2/stimela/cargo/cab/wsclean.yaml, origin: /home/ramaila/software/stimela2/stimela                          
2022-10-25 16:46:09 STIMELA DEBUG: config dependency /home/ramaila/software/stimela2/stimela/cargo/cab/casa_applycal.yaml, origin: /home/ramaila/software/stimela2/stimela                    
2022-10-25 16:46:09 STIMELA DEBUG: config dependency /home/ramaila/software/stimela2/stimela/cargo/cab/simms.yaml, origin: /home/ramaila/software/stimela2/stimela                            
2022-10-25 16:46:09 STIMELA DEBUG: config dependency /home/ramaila/software/stimela2/stimela/cargo/cab/wsclean_pol.yaml, origin: /home/ramaila/software/stimela2/stimela                      
2022-10-25 16:46:09 STIMELA DEBUG: config dependency /home/ramaila/software/stimela2/stimela/cargo/cab/shadems.yaml, origin: /home/ramaila/software/stimela2/stimela                          
2022-10-25 16:46:09 STIMELA INFO: saving config dependencies to ./stimela.config.deps                                                                                                         
2022-10-25 16:46:09 STIMELA ERROR: 'pica-time.yml' is neither a recipe file nor a known stimela cab                                                                                    
str: 'pica-time.yml' is neither a recipe file nor a known stimela cab
```

am i missing something?

**Comment by o-smirnov** [comment]
Where are you running -- which venv -- can I try myself as you?

**Comment by o-smirnov** [comment]
The code says

```python
      if not os.path.isfile(what):
            log_exception(f"'{what}' is neither a recipe file nor a known stimela cab")
            sys.exit(2)
```

...so this is possible only if your recipe has gone missing somehow?

**Comment by Athanaseus** [comment]
> ...so this is possible only if your recipe has gone missing somehow?

Yes, this was the case, wrong directory. The recipe file didn't exist.

I had previously removed this block.
```
    # for nodes with an SSD scratch space, change default directory assignments
    run.node:
      hall:
        dirs: 
          temp: /scratch/{config.run.env.USER}/ESO137
          base: /scratch/{config.run.env.USER}/ESO137
        ncpu: 64
```
Now I get
```
2022-10-25 17:41:51 STIMELA ERROR: pre-validation of recipe 'pictor' failed                                                                                                            
pre-validation of recipe 'pictor' failed
├── pictor.assign_based_on.run.node: unknown value 'crosby', and no default defined
└── Traceback:
    ├──   File "/home/ramaila/software/stimela2/stimela/commands/run.py", line 216, in run
    │       params = outer_step.prevalidate(root=True)
    ├──   File "/home/ramaila/software/stimela2/stimela/kitchen/step.py", line 253, in prevalidate
    │       params = self.validated_params = self.cargo.prevalidate(self.params, subst, root=root)
    ├──   File "/home/ramaila/software/stimela2/stimela/kitchen/recipe.py", line 605, in prevalidate
    │       self.update_assignments(subst, params=params, ignore_subst_errors=True)
    └──   File "/home/ramaila/software/stimela2/stimela/kitchen/recipe.py", line 223, in update_assignments
            raise AssignmentError(f"{whose.fqname}.assign_based_on.{basevar}: unknown value '{value}', and no default defined")
2022-10-25 17:41:51 STIMELA DEBUG: Traceback (most recent call last):                                                                                                                         
2022-10-25 17:41:51 STIMELA DEBUG:   File "/home/ramaila/software/stimela2/stimela/commands/run.py", line 216, in run                                                                         
2022-10-25 17:41:51 STIMELA DEBUG:     params = outer_step.prevalidate(root=True)                                                                                                             
2022-10-25 17:41:51 STIMELA DEBUG:   File "/home/ramaila/software/stimela2/stimela/kitchen/step.py", line 253, in prevalidate                                                                 
2022-10-25 17:41:51 STIMELA DEBUG:     params = self.validated_params = self.cargo.prevalidate(self.params, subst, root=root)                                                                 
2022-10-25 17:41:51 STIMELA DEBUG:   File "/home/ramaila/software/stimela2/stimela/kitchen/recipe.py", line 605, in prevalidate                                                               
2022-10-25 17:41:51 STIMELA DEBUG:     self.update_assignments(subst, params=params, ignore_subst_errors=True)                                                                                
2022-10-25 17:41:51 STIMELA DEBUG:   File "/home/ramaila/software/stimela2/stimela/kitchen/recipe.py", line 223, in update_assignments                                                        
2022-10-25 17:41:51 STIMELA DEBUG:     raise AssignmentError(f"{whose.fqname}.assign_based_on.{basevar}: unknown value '{value}', and no default defined")                                    
2022-10-25 17:41:51 STIMELA DEBUG: stimela.exceptions.AssignmentError: pictor.assign_based_on.run.node: unknown value 'crosby', and no default defined                                        
2022-10-25 17:41:51 STIMELA DEBUG: 
```

**Comment by o-smirnov** [comment]
You need to add an empty DEFAULT section like so. Make sure it's at the same level as the "hall" entry. Or just take the run.node entry out entirely for now.

```yaml
 run.node:
      hall:
        dirs: 
          temp: /scratch/{config.run.env.USER}/ESO137
          base: /scratch/{config.run.env.USER}/ESO137
        ncpu: 64
      DEFAULT:
```

**Comment by Athanaseus** [comment]
The error above is due to block being removed entirely.
Adding `DEFAULT` as above results with the same error.
Even with
```
    run.node:
      hall:
      DEFAULT:
```
and
```
    run.node:
      DEFAULT:
```

**Comment by o-smirnov** [comment]
OK let me see for myself. Host, directory, venv?

**Comment by Athanaseus** [comment]
crosby: `/home/ramaila/software/pica`

recipe: `pica-time.yml`

venv: `stimulator`

command: `stimela -v -C run -s calibrate-0:image_pol-0 pica-time.yml pictor`

**Comment by o-smirnov** [comment]
Well, I commented out the ``run.node`` section, and it gets past that error now, so not sure what you did differently before?

**Comment by Athanaseus** [comment]
Yes, now with the block commented out works. But with the `DEFAULT` I get the following:

```
2022-10-25 22:39:14 STIMELA ERROR: pre-validation of recipe 'pictor' failed
pre-validation of recipe 'pictor' failed
├── pictor.assign_based_on.run.node.DEFAULT: mapping expected, got <class 'NoneType'> instead
└── Traceback:
    ├──   File "/home/ramaila/software/stimela2/stimela/commands/run.py", line 216, in run
    │       params = outer_step.prevalidate(root=True)
    ├──   File "/home/ramaila/software/stimela2/stimela/kitchen/step.py", line 253, in prevalidate
    │       params = self.validated_params = self.cargo.prevalidate(self.params, subst, root=root)
    ├──   File "/home/ramaila/software/stimela2/stimela/kitchen/recipe.py", line 605, in prevalidate
    │       self.update_assignments(subst, params=params, ignore_subst_errors=True)
    └──   File "/home/ramaila/software/stimela2/stimela/kitchen/recipe.py", line 227, in update_assignments
            raise AssignmentError(f"{whose.fqname}.assign_based_on.{basevar}.{value}: mapping expected, got {type(assignments)} instead")
```

The original problem seems to be solved. A defined variable or valid evaluation is required to skip. 

```
2022-10-25 22:53:34 STIMELA.pictor.calibrate-0 DEBUG: dynamic skip attribute evaluation returns {'skip': UNSET(value='recipe.blah', errors=[UnsetError("'recipe.blah' undefined")])}
2022-10-25 22:53:34 STIMELA ERROR: error running step 'calibrate-0'
error running step 'calibrate-0'
├── pictor.calibrate-0.skip: error evaluating '=recipe.blah'
│   └── 'recipe.blah' undefined
└── Traceback:
    ├──   File "/home/ramaila/software/stimela2/stimela/kitchen/recipe.py", line 951, in loop_worker
    │       step_params = step.run(subst=subst.copy(), parent_log=self.log)  # make a copy of the subst dict since recipe might modify
    └──   File "/home/ramaila/software/stimela2/stimela/kitchen/step.py", line 293, in run
            raise StepValidationError(f"{self.fqname}.skip: error evaluating '{self.skip}'", skip.errors)
2022-10-25 22:53:34 STIMELA DEBUG: Traceback (most recent call last):
2022-10-25 22:53:34 STIMELA DEBUG:   File "/home/ramaila/software/stimela2/stimela/commands/run.py", line 327, in run
2022-10-25 22:53:34 STIMELA DEBUG:     outputs = outer_step.run()
2022-10-25 22:53:34 STIMELA DEBUG:   File "/home/ramaila/software/stimela2/stimela/kitchen/step.py", line 352, in run
2022-10-25 22:53:34 STIMELA DEBUG:     self.cargo._run(params, subst)
2022-10-25 22:53:34 STIMELA DEBUG:   File "/home/ramaila/software/stimela2/stimela/kitchen/recipe.py", line 983, in _run
2022-10-25 22:53:34 STIMELA DEBUG:     results = [loop_worker(*args) for args in loop_futures]
2022-10-25 22:53:34 STIMELA DEBUG:   File "/home/ramaila/software/stimela2/stimela/kitchen/recipe.py", line 983, in <listcomp>
2022-10-25 22:53:34 STIMELA DEBUG:     results = [loop_worker(*args) for args in loop_futures]
2022-10-25 22:53:34 STIMELA DEBUG:   File "/home/ramaila/software/stimela2/stimela/kitchen/recipe.py", line 951, in loop_worker
2022-10-25 22:53:34 STIMELA DEBUG:     step_params = step.run(subst=subst.copy(), parent_log=self.log)  # make a copy of the subst dict since recipe might modify
2022-10-25 22:53:34 STIMELA DEBUG:   File "/home/ramaila/software/stimela2/stimela/kitchen/step.py", line 293, in run
2022-10-25 22:53:34 STIMELA DEBUG:     raise StepValidationError(f"{self.fqname}.skip: error evaluating '{self.skip}'", skip.errors)
2022-10-25 22:53:34 STIMELA DEBUG: stimela.exceptions.StepValidationError: pictor.calibrate-0.skip: error evaluating '=recipe.blah': 'recipe.blah' undefined

**Comment by o-smirnov** [comment]
OK I've pushed a fix which should make an empty ``DEFAULT:`` work.

**Comment by Athanaseus** [comment]
All cases above with `DEFAULT:` work fine.

**Comment by o-smirnov** [comment]
Cool, thanks for testing!
