### ISSUE TITLE
scabha doesn't get installed unless in dev mode 

### ISSUE THREAD

**Issue by landmanbester** [caracal-pipeline/stimela2#85]
Never seen this before but I suspect recent switch to poetry may somehow be involved. I am installing stimela in pfb-clean by adding
```
"stimela"
"@git+https://github.com/caracal-pipeline/stimela2"
"@master"
``` 
to requirements in setup.py. The weird thing is it seems to install successfully 
```
Successfully installed Click-8.1.3 Jinja2-3.1.2 MarkupSafe-2.1.1 PyWavelets-1.4.1 PyYAML-6.0 absl-py-1.3.0 aiobotocore-2.4.0 aiohttp-3.8.3 aioitertools-0.11.0 aiosignal-1.2.0 antlr4-python3-runtime-4.9.3 appdirs-1.4.4 asciitree-0.3.3 astropy-5.1.1 asttokens-2.1.0 async-timeout-4.0.2 attrs-22.1.0 backcall-0.2.0 bokeh-3.0.0 botocore-1.27.59 certifi-2022.9.24 charset-normalizer-2.1.1 cloudpickle-2.2.0 codex-africanus-0.3.3 commonmark-0.9.1 contourpy-1.0.6 cycler-0.11.0 dask-2022.10.2 dask-ms-0.2.15 dataclasses-0.6 decorator-5.1.1 dill-0.3.6 distributed-2022.10.2 donfig-0.7.0 ducc0-0.27.0 entrypoints-0.4 etils-0.9.0 exceptiongroup-1.0.0 executing-1.2.0 fasteners-0.18 flake8-4.0.1 flaky-3.7.0 fonttools-4.38.0 frozenlist-1.3.1 fsspec-2022.10.0 graphviz-0.20.1 heapdict-1.0.1 idna-3.4 imageio-2.22.3 importlib-metadata-5.0.0 importlib_resources-5.10.0 iniconfig-1.1.1 ipython-8.6.0 jax-0.3.23 jaxlib-0.3.22 jedi-0.18.1 jmespath-1.0.1 jsonschema-3.2.0 katbeam-0.1 kiwisolver-1.4.4 llvmlite-0.39.1 locket-1.0.0 matplotlib-3.6.1 matplotlib-inline-0.1.6 mccabe-0.6.1 mpmath-1.2.1 msgpack-1.0.4 multidict-6.0.2 munch-2.5.0 networkx-2.8.8 nifty7-7.5 numba-0.56.3 numcodecs-0.10.2 numexpr-2.8.4 numpy-1.22.0 omegaconf-2.2.3 opt-einsum-3.3.0 packaging-21.3 packratt-0.1.3 pandas-1.5.1 parso-0.8.3 partd-1.3.0 pexpect-4.8.0 pfb-clean-0.0.1 pickleshare-0.7.5 pillow-9.3.0 pluggy-1.0.0 prompt-toolkit-3.0.31 psutil-5.9.3 ptyprocess-0.7.0 pure-eval-0.2.2 pycodestyle-2.8.0 pydantic-1.10.2 pyerfa-2.0.0.1 pyflakes-2.4.0 pygments-2.13.0 pyparsing-3.0.9 pyrsistent-0.19.1 pyscilog-0.1.2 pytest-7.2.0 pytest-flake8-1.1.1 python-casacore-3.5.2 python-dateutil-2.8.2 pytz-2022.6 requests-2.28.1 rich-12.6.0 s3fs-2022.10.0 scikit-image-0.19.3 scipy-1.9.3 six-1.16.0 sortedcontainers-2.4.0 stack-data-0.6.0 stimela-2.0rc2 sympy-1.11.1 tblib-1.7.0 tifffile-2022.10.10 tomli-2.0.1 toolz-0.12.0 tornado-6.1 traitlets-5.5.0 typing-extensions-4.4.0 urllib3-1.26.12 wcwidth-0.2.5 wrapt-1.14.1 xarray-2022.10.0 xyzservices-2022.9.0 yarl-1.8.1 zarr-2.13.3 zict-2.2.0 zipp-3.10.0
``` 
but if I try to import scabha I get
```
(pfb) ╭─landman@LAPTOP-ED4N50Q2 ~/software
╰─➤  python
Python 3.8.10 (default, Mar 15 2022, 12:22:08)
[GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import scabha
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'scabha'
```
However, if I install stimela in dev mode using
```
$ pip install -e stimela
```
I can import scabha just fine. Please help @SpheMakh or @sjperkins?

**Comment by landmanbester** [comment]
Ah, it's way simpler to reproduce than that. scabha is not installed unless you install in dev mode.
```
 pip install stimela2/                                                                                          1 ↵
Processing ./stimela2
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting rich<13.0.0,>=12.6.0
  Using cached rich-12.6.0-py3-none-any.whl (237 kB)
Collecting munch<3.0.0,>=2.5.0
  Using cached munch-2.5.0-py2.py3-none-any.whl (10 kB)
Collecting click<9.0.0,>=8.1.3
  Using cached click-8.1.3-py3-none-any.whl (96 kB)
Collecting dill<0.4.0,>=0.3.6
  Using cached dill-0.3.6-py3-none-any.whl (110 kB)
Collecting omegaconf<3.0,>=2.1
  Using cached omegaconf-2.2.3-py3-none-any.whl (79 kB)
Collecting pyparsing<4.0.0,>=3.0.9
  Using cached pyparsing-3.0.9-py3-none-any.whl (98 kB)
Collecting pydantic<2.0.0,>=1.10.2
  Using cached pydantic-1.10.2-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (13.6 MB)
Collecting psutil<6.0.0,>=5.9.3
  Using cached psutil-5.9.3-cp38-cp38-manylinux_2_12_x86_64.manylinux2010_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl (295 kB)
Collecting six
  Using cached six-1.16.0-py2.py3-none-any.whl (11 kB)
Collecting PyYAML>=5.1.0
  Using cached PyYAML-6.0-cp38-cp38-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_12_x86_64.manylinux2010_x86_64.whl (701 kB)
Collecting antlr4-python3-runtime==4.9.*
  Using cached antlr4_python3_runtime-4.9.3-py3-none-any.whl
Collecting typing-extensions>=4.1.0
  Using cached typing_extensions-4.4.0-py3-none-any.whl (26 kB)
Collecting pygments<3.0.0,>=2.6.0
  Using cached Pygments-2.13.0-py3-none-any.whl (1.1 MB)
Collecting commonmark<0.10.0,>=0.9.0
  Using cached commonmark-0.9.1-py2.py3-none-any.whl (51 kB)
Building wheels for collected packages: stimela
  Building wheel for stimela (pyproject.toml) ... done
  Created wheel for stimela: filename=stimela-2.0rc2-py3-none-any.whl size=125793 sha256=737b950be85474175a101142770b1f822532ea503e6c288c877dc3dcf83c4ed5
  Stored in directory: /tmp/pip-ephem-wheel-cache-y2r6d24_/wheels/dd/e0/82/dbe89459af92745dec277a5ead1810d7c1616fb4dd88da590e
Successfully built stimela
Installing collected packages: commonmark, antlr4-python3-runtime, typing-extensions, six, PyYAML, pyparsing, pygments, psutil, dill, click, rich, pydantic, omegaconf, munch, stimela
Successfully installed PyYAML-6.0 antlr4-python3-runtime-4.9.3 click-8.1.3 commonmark-0.9.1 dill-0.3.6 munch-2.5.0 omegaconf-2.2.3 psutil-5.9.3 pydantic-1.10.2 pygments-2.13.0 pyparsing-3.0.9 rich-12.6.0 six-1.16.0 stimela-2.0rc2 typing-extensions-4.4.0
(stimela) ╭─landman@LAPTOP-ED4N50Q2 ~/software
╰─➤  python
Python 3.8.10 (default, Mar 15 2022, 12:22:08)
[GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import scabha
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'scabha'
>>>
```
Adding { include = "scabha" } to the .toml file seems to fix the problem

**Comment by landmanbester** [comment]
Nope, I spoke too soon. Although I can import scabha it now falls over with
```
pfb init --ms MS/point_gauss_nb.MS_p0 --output-filename out/test --nband 4 --product I --nthreads 8 --scheduler distributed --overwrite
Error loading cached config from /home/landman/.cache/configuratt/77c2256f2c33dfbba5377ea71168501a: Ran out of input. Removing the cache.
Traceback (most recent call last):
  File "/home/landman/venvs/pfb/bin/pfb", line 33, in <module>
    sys.exit(load_entry_point('pfb-clean', 'console_scripts', 'pfb')())
  File "/home/landman/venvs/pfb/bin/pfb", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/usr/lib/python3.8/importlib/metadata.py", line 77, in load
    module = import_module(match.group('module'))
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/landman/software/pfb-clean/pfb/workers/main.py", line 10, in <module>
    from pfb.workers import (init, grid, degrid,
  File "/home/landman/software/pfb-clean/pfb/workers/init.py", line 11, in <module>
    from pfb.parser.schemas import schema
  File "/home/landman/software/pfb-clean/pfb/parser/schemas.py", line 26, in <module>
    tmp = configuratt.load_nested(files,
  File "/home/landman/venvs/pfb/lib/python3.8/site-packages/scabha/configuratt/__init__.py", line 155, in load_nested
    save_cache(filelist, section_content, dependencies, verbose=verbose)
  File "/home/landman/venvs/pfb/lib/python3.8/site-packages/scabha/configuratt/cache.py", line 93, in save_cache
    pickle.dump((conf, deps), open(filename, "wb"), 2)
  File "/home/landman/venvs/pfb/lib/python3.8/site-packages/dill/_dill.py", line 235, in dump
    Pickler(file, protocol, **_kwds).dump(obj)
  File "/home/landman/venvs/pfb/lib/python3.8/site-packages/dill/_dill.py", line 394, in dump
    StockPickler.dump(self, obj)
  File "/usr/lib/python3.8/pickle.py", line 487, in dump
    self.save(obj)
  File "/home/landman/venvs/pfb/lib/python3.8/site-packages/dill/_dill.py", line 388, in save
    StockPickler.save(self, obj, save_persistent_id)
  File "/usr/lib/python3.8/pickle.py", line 560, in save
    f(self, obj)  # Call unbound method with explicit self
  File "/usr/lib/python3.8/pickle.py", line 886, in save_tuple
    save(element)
  File "/home/landman/venvs/pfb/lib/python3.8/site-packages/dill/_dill.py", line 388, in save
    StockPickler.save(self, obj, save_persistent_id)
  File "/usr/lib/python3.8/pickle.py", line 560, in save
    f(self, obj)  # Call unbound method with explicit self
  File "/home/landman/venvs/pfb/lib/python3.8/site-packages/dill/_dill.py", line 1186, in save_module_dict
    StockPickler.save_dict(pickler, obj)
  File "/usr/lib/python3.8/pickle.py", line 971, in save_dict
    self._batch_setitems(obj.items())
  File "/usr/lib/python3.8/pickle.py", line 997, in _batch_setitems
    save(v)
  File "/home/landman/venvs/pfb/lib/python3.8/site-packages/dill/_dill.py", line 388, in save
    StockPickler.save(self, obj, save_persistent_id)
  File "/usr/lib/python3.8/pickle.py", line 603, in save
    self.save_reduce(obj=obj, *rv)
  File "/usr/lib/python3.8/pickle.py", line 717, in save_reduce
    save(state)
  File "/home/landman/venvs/pfb/lib/python3.8/site-packages/dill/_dill.py", line 388, in save
    StockPickler.save(self, obj, save_persistent_id)
  File "/usr/lib/python3.8/pickle.py", line 560, in save
    f(self, obj)  # Call unbound method with explicit self
  File "/home/landman/venvs/pfb/lib/python3.8/site-packages/dill/_dill.py", line 1186, in save_module_dict
    StockPickler.save_dict(pickler, obj)
  File "/usr/lib/python3.8/pickle.py", line 971, in save_dict
    self._batch_setitems(obj.items())
  File "/usr/lib/python3.8/pickle.py", line 997, in _batch_setitems
    save(v)
  File "/home/landman/venvs/pfb/lib/python3.8/site-packages/dill/_dill.py", line 388, in save
    StockPickler.save(self, obj, save_persistent_id)
  File "/usr/lib/python3.8/pickle.py", line 603, in save
    self.save_reduce(obj=obj, *rv)
  File "/usr/lib/python3.8/pickle.py", line 717, in save_reduce
    save(state)
  File "/home/landman/venvs/pfb/lib/python3.8/site-packages/dill/_dill.py", line 388, in save
    StockPickler.save(self, obj, save_persistent_id)
  File "/usr/lib/python3.8/pickle.py", line 560, in save
    f(self, obj)  # Call unbound method with explicit self
  File "/home/landman/venvs/pfb/lib/python3.8/site-packages/dill/_dill.py", line 1186, in save_module_dict
    StockPickler.save_dict(pickler, obj)
  File "/usr/lib/python3.8/pickle.py", line 971, in save_dict
    self._batch_setitems(obj.items())
  File "/usr/lib/python3.8/pickle.py", line 997, in _batch_setitems
    save(v)
  File "/home/landman/venvs/pfb/lib/python3.8/site-packages/dill/_dill.py", line 388, in save
    StockPickler.save(self, obj, save_persistent_id)
  File "/usr/lib/python3.8/pickle.py", line 560, in save
    f(self, obj)  # Call unbound method with explicit self
  File "/home/landman/venvs/pfb/lib/python3.8/site-packages/dill/_dill.py", line 1698, in save_type
    _save_with_postproc(pickler, (_create_type, (
  File "/home/landman/venvs/pfb/lib/python3.8/site-packages/dill/_dill.py", line 1084, in _save_with_postproc
    pickler._batch_setitems(iter(source.items()))
  File "/usr/lib/python3.8/pickle.py", line 997, in _batch_setitems
    save(v)
  File "/home/landman/venvs/pfb/lib/python3.8/site-packages/dill/_dill.py", line 388, in save
    StockPickler.save(self, obj, save_persistent_id)
  File "/usr/lib/python3.8/pickle.py", line 560, in save
    f(self, obj)  # Call unbound method with explicit self
  File "/home/landman/venvs/pfb/lib/python3.8/site-packages/dill/_dill.py", line 1266, in save_generic_alias
    StockPickler.save_global(pickler, obj, name=obj.__reduce__())
  File "/usr/lib/python3.8/pickle.py", line 1070, in save_global
    raise PicklingError(
_pickle.PicklingError: Can't pickle typing.AbstractContextManager: it's not found as typing.AbstractContextManager
```
Any ideas @o-smirnov?

**Comment by landmanbester** [comment]
I can get around the above error by disabling use_cache when calling load_nested but my optional parameters still come back as ```'<UNSET DEFAULT VALUE>'``` instead of ```None```. It's a bit annoying having to manually convert them to None

**Comment by landmanbester** [comment]
Ok, changing ```UNSET``` to ```_UNSET_DEFAULT``` in schema_utils.py fixes that problem. Next problem, my terminal gets spammed by 
```
Error loading cached config from /home/landman/.cache/configuratt/42e84839b1bd0f40ef88b73ab97a37df: cached deps object is of type <class 'set'>, expecting ConfigDependencies. Removing the cache.
Error loading cached config from /home/landman/.cache/configuratt/b8d12bcf36239320485270795babefee: cached deps object is of type <class 'set'>, expecting ConfigDependencies. Removing the cache.
Error loading cached config from /home/landman/.cache/configuratt/250c587e3ee2c87983371b8729ac9ab2: cached deps object is of type <class 'set'>, expecting ConfigDependencies. Removing the cache.
Error loading cached config from /home/landman/.cache/configuratt/a03103a2b5768697fae4dfe4bfd80d57: cached deps object is of type <class 'set'>, expecting ConfigDependencies. Removing the cache.
Error loading cached config from /home/landman/.cache/configuratt/7227eb82c8bb51e6e83987f18deed33a: cached deps object is of type <class 'set'>, expecting ConfigDependencies. Removing the cache.
Error loading cached config from /home/landman/.cache/configuratt/00a41a4813242be557938b2110bd8176: cached deps object is of type <class 'set'>, expecting ConfigDependencies. Removing the cache.
Error loading cached config from /home/landman/.cache/configuratt/3efcd4839de9a7d380a34d8aa3aeb3c8: cached deps object is of type <class 'set'>, expecting ConfigDependencies. Removing the cache.
Error loading cached config from /home/landman/.cache/configuratt/1bf3c3fcc19f33a8dbb173aa2de2d129: cached deps object is of type <class 'set'>, expecting ConfigDependencies. Removing the cache.
Error loading cached config from /home/landman/.cache/configuratt/5029a103c0fc5d0022394f33c7ae2c68: cached deps object is of type <class 'set'>, expecting ConfigDependencies. Removing the cache.
Error loading cached config from /home/landman/.cache/configuratt/3b9fd584b42fac9badfc6f0f06f4847f: cached deps object is of type <class 'set'>, expecting ConfigDependencies. Removing the cache.
Error loading cached config from /home/landman/.cache/configuratt/d5ffceb78e586d69de481f9440f7d02c: cached deps object is of type <class 'set'>, expecting ConfigDependencies. Removing the cache.
Error loading cached config from /home/landman/.cache/configuratt/e0d3eb7598cb2ee73e0c1b12951f995c: cached deps object is of type <class 'set'>, expecting ConfigDependencies. Removing the cache.
Error loading cached config from /home/landman/.cache/configuratt/d93ce289c30ad995d6ddfab443511ed0: cached deps object is of type <class 'set'>, expecting ConfigDependencies. Removing the cache.
Error loading cached config from /home/landman/.cache/configuratt/3808ab24bd53e31f65e712eeb878ce6b: cached deps object is of type <class 'set'>, expecting ConfigDependencies. Removing the cache.
Error loading cached config from /home/landman/.cache/configuratt/3df9594ebea52a11638c53c7033404ae: cached deps object is of type <class 'set'>, expecting ConfigDependencies. Removing the cache.
Error loading cached config from /home/landman/.cache/configuratt/75f5e703dd1446e3a7e7040bc948a2af: cached deps object is of type <class 'set'>, expecting ConfigDependencies. Removing the cache.
Error loading cached config from /home/landman/.cache/configuratt/0b853d7f11a3b20a1f9fca8f658cc272: cached deps object is of type <class 'set'>, expecting ConfigDependencies. Removing the cache.
Error loading cached config from /home/landman/.cache/configuratt/b127c9a61aff37cc013cbfaad8eeec8b: cached deps object is of type <class 'set'>, expecting ConfigDependencies. Removing the cache.
Error loading cached config from /home/landman/.cache/configuratt/168d1b0ef2101e213531b82d634f0a7f: cached deps object is of type <class 'set'>, expecting ConfigDependencies. Removing the cache.
Error loading cached config from /home/landman/.cache/configuratt/580beb827245b03deec6b22f1f54aa43: cached deps object is of type <class 'set'>, expecting ConfigDependencies. Removing the cache.
Error loading cached config from /home/landman/.cache/configuratt/a380ac35d145b380521a140319c28c5e: cached deps object is of type <class 'set'>, expecting ConfigDependencies. Removing the cache.
Error loading cached config from /home/landman/.cache/configuratt/a81dda192e83471b568fd11f3fa51eb3: cached deps object is of type <class 'set'>, expecting ConfigDependencies. Removing the cache.
Error loading cached config from /home/landman/.cache/configuratt/c2b631f5bd1da9c9320eeec7b29b7a0b: cached deps object is of type <class 'set'>, expecting ConfigDependencies. Removing the cache.
Error loading cached config from /home/landman/.cache/configuratt/cb3f89739740b11468f7b4d47c025f71: cached deps object is of type <class 'set'>, expecting ConfigDependencies. Removing the cache.
Error loading cached config from /home/landman/.cache/configuratt/6d28f068568a3708dcd60eac89e407f6: cached deps object is of type <class 'set'>, expecting ConfigDependencies. Removing the cache.
```
Why is it caching if I set use_cache=False in load_nested?

**Comment by o-smirnov** [comment]
Geez WTF. Can has reproducer please?

Surprised ``import scabha`` works at all, it should be ``from stimela import scabha`` ever since we rolled scabha into stimela.

**Comment by landmanbester** [comment]
Just do a local install and try to import scabha 
```
$ pip install stimela2/
Processing ./stimela2
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting dill<0.4.0,>=0.3.6
  Using cached dill-0.3.6-py3-none-any.whl (110 kB)
Collecting click<9.0.0,>=8.1.3
  Using cached click-8.1.3-py3-none-any.whl (96 kB)
Collecting munch<3.0.0,>=2.5.0
  Using cached munch-2.5.0-py2.py3-none-any.whl (10 kB)
Collecting omegaconf<3.0,>=2.1
  Using cached omegaconf-2.2.3-py3-none-any.whl (79 kB)
Collecting pydantic<2.0.0,>=1.10.2
  Using cached pydantic-1.10.2-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (13.6 MB)
Collecting psutil<6.0.0,>=5.9.3
  Using cached psutil-5.9.3-cp38-cp38-manylinux_2_12_x86_64.manylinux2010_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl (295 kB)
Collecting rich<13.0.0,>=12.6.0
  Using cached rich-12.6.0-py3-none-any.whl (237 kB)
Collecting pyparsing<4.0.0,>=3.0.9
  Using cached pyparsing-3.0.9-py3-none-any.whl (98 kB)
Collecting six
  Using cached six-1.16.0-py2.py3-none-any.whl (11 kB)
Collecting antlr4-python3-runtime==4.9.*
  Using cached antlr4_python3_runtime-4.9.3-py3-none-any.whl
Collecting PyYAML>=5.1.0
  Using cached PyYAML-6.0-cp38-cp38-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_12_x86_64.manylinux2010_x86_64.whl (701 kB)
Collecting typing-extensions>=4.1.0
  Using cached typing_extensions-4.4.0-py3-none-any.whl (26 kB)
Collecting commonmark<0.10.0,>=0.9.0
  Using cached commonmark-0.9.1-py2.py3-none-any.whl (51 kB)
Collecting pygments<3.0.0,>=2.6.0
  Using cached Pygments-2.13.0-py3-none-any.whl (1.1 MB)
Building wheels for collected packages: stimela
  Building wheel for stimela (pyproject.toml) ... done
  Created wheel for stimela: filename=stimela-2.0rc2-py3-none-any.whl size=208714 sha256=2ded5d30cace91fa34e767cc8d26b11718ceb269eb462dc344521fa237c9ecf2
  Stored in directory: /tmp/pip-ephem-wheel-cache-0c478hbp/wheels/dd/e0/82/dbe89459af92745dec277a5ead1810d7c1616fb4dd88da590e
Successfully built stimela
Installing collected packages: commonmark, antlr4-python3-runtime, typing-extensions, six, PyYAML, pyparsing, pygments, psutil, dill, click, rich, pydantic, omegaconf, munch, stimela
Successfully installed PyYAML-6.0 antlr4-python3-runtime-4.9.3 click-8.1.3 commonmark-0.9.1 dill-0.3.6 munch-2.5.0 omegaconf-2.2.3 psutil-5.9.3 pydantic-1.10.2 pygments-2.13.0 pyparsing-3.0.9 rich-12.6.0 six-1.16.0 stimela-2.0rc2 typing-extensions-4.4.0
(stimela) ╭─landman@LAPTOP-ED4N50Q2 ~/software
╰─➤  ipython
zsh: command not found: ipython
(stimela) ╭─landman@LAPTOP-ED4N50Q2 ~/software
╰─➤  python                                                                                                       127 ↵
Python 3.8.10 (default, Mar 15 2022, 12:22:08)
[GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from stimela import scabha
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/landman/venvs/stimela/lib/python3.8/site-packages/stimela/__init__.py", line 25, in <module>
    from .stimelogging import logger, log_exception
  File "/home/landman/venvs/stimela/lib/python3.8/site-packages/stimela/stimelogging.py", line 9, in <module>
    from scabha.exceptions import ScabhaBaseException, FormattedTraceback
ModuleNotFoundError: No module named 'scabha'
```
Note I am trying to import scabha from stimela here. ```import scabha``` also fails

**Comment by o-smirnov** [comment]
Ah nvm my branch, I see your PR already fixes this.

> Surprised import scabha works at all, it should be from stimela import scabha ever since we rolled scabha into stimela.

Forget I said this. ``import scabha`` should work. But I'm puzzled how it worked at all previously (and how it passed any tests?)

**Comment by o-smirnov** [comment]
> Ok, changing UNSET to _UNSET_DEFAULT in schema_utils.py fixes that problem. Next problem, my terminal gets spammed by

@landmanbester is this still a problem and should we break it out into a new issue if so?

**Comment by landmanbester** [comment]
It's not a big deal but I do get spammed with those messages from time to time. I will open a separate issue if it keeps happening. Not sure why it would complain about the cache if I disabled it. Do things still get cached under the hood somewhere?

**Comment by o-smirnov** [comment]
Probably shouldn't try to read it at all -- I'll have a look at that logic again.

**Comment by o-smirnov** [comment]
``load_nested`` does say
```python
section_content, dependencies = load_cache(filelist, verbose=verbose) if use_cache else (None, None)
```
...so I dunno WTF, please open issue if you see it again!
